### ISSUE TITLE
Error on tests

### ISSUE THREAD

**Issue by mateusgalasso** [binarybuilds/laravel-mail-manager#1]
ErrorException : array_values() expects parameter 1 to be array, null given
 C:\SGP-Laravel\vendor\binarybuilds\laravel-mail-manager\src\Managers\NotificationManager.php:31

But I'm using App\User from Laravel

/**
     * Route notifications for the mail channel.
     *
     * @param Notification $notification
     * @return string
     */
    public function routeNotificationForMail($notification)
    {
        return $this->ds_email;
    }

and this user has email

Works when is not in test environment

**Comment by srinathreddydudi** [comment]
@stonkeep Thank you for identifying and creating an issue for this bug. This is now fixed in the latest release 1.0.1.
