### ISSUE TITLE
Cant get it installed in Laravel 8 

### ISSUE THREAD

**Issue by dajoeberlei** [binarybuilds/laravel-mail-manager#3]
When trying to require the package via composer in an laravel 8 project i get the error:
![image](https://user-images.githubusercontent.com/9009638/97555616-9fd37d80-19d8-11eb-812c-917aa350dbe7.png)

**Comment by srinathreddydudi** [comment]
@dajoeberlei This is fixed in the latest release https://github.com/binarybuilds/laravel-mail-manager/releases/tag/v1.1.0
